#!/bin/bash
# traverse source rnc files and compile into apropriate rng file, mirroring source directory structure.

scriptpath=`readlink -f $0`
scriptdir=${scriptpath%/*}
sourcedir=$scriptdir/source
outdir=$scriptdir/build

cd scriptpath

for rncpath in `ls $sourcedir/*/*/*.rnc`
do
    rncpath=${rncpath##*/source/}
    rngpath=$outdir/${rncpath%.rnc}.rng
    rngdir=${rngpath%/*.rng}
    echo rncpath=$rncpath 
    echo   rngpath=$rngpath
    echo   rngdir=$rngdir
    mkdir -p $rngdir
    java -jar $scriptdir/trang.jar -I rnc -O rng $rncpath $rngpath
done
exit 0

#java -jar trang.jar -I rnc -O rng usx.rnc usx.rng
#java -jar trang.jar -I rnc -O rng metadata_project.rnc metadata_project.rng
#java -jar trang.jar -I rnc -O rng usx_styles.rnc usx_styles.rng
