#!/bin/bash
# traverse source rnc files and compile into apropriate rng file, mirroring source directory structure.

scriptpath=`readlink -f $0`
scriptdir=${scriptpath%/*}
sourcedir=$scriptdir/source
outdir=$scriptdir/build

cd #scriptpath
rm -rf $outdir

for rncpath in `ls $sourcedir/*/*/*.rnc`
do
    relpath=${rncpath##*/source/}
    rngpath=$outdir/${relpath%.rnc}.rng
    xsdpath=$outdir/${relpath%.rnc}.dtd
    rngdir=${rngpath%/*.rng}
#    echo rncpath=$rncpath 
#    echo   rngpath=$rngpath
#    echo   rngdir=$rngdir
    echo "Converting $relpath "
    mkdir -p $rngdir
    java -jar $scriptdir/trang.jar -I rnc -O rng $rncpath $rngpath
    #This should work, but dtd doesn't appear to be able to handle everything RNG can
    #java -jar $scriptdir/trang.jar -I rnc -O dtd $rncpath $xsdpath
done
exit 0

#java -jar trang.jar -I rnc -O rng usx.rnc usx.rng
#java -jar trang.jar -I rnc -O rng metadata_project.rnc metadata_project.rng
#java -jar trang.jar -I rnc -O rng usx_styles.rnc usx_styles.rng
