#!/bin/bash
# traverse source rnc files and compile into apropriate rng file, mirroring source directory structure.

scriptpath=`readlink -f $0`
scriptdir=${scriptpath%/*}
sourcedir=$scriptdir/$1

for rnc in `ls $sourcedir/*.rnc`
do
    base=${rnc##*/}
    base=${base%.rnc}
    java -jar $scriptdir/trang.jar -I rnc -O rng $rnc $base.rng
done
exit 0
java -jar trang.jar -I rnc -O rng usx.rnc usx.rng
java -jar trang.jar -I rnc -O rng metadata_project.rnc metadata_project.rng
java -jar trang.jar -I rnc -O rng usx_styles.rnc usx_styles.rng
