#!/bin/bash
# Compare the validation results of one metadata.xml file using the old (Jeff's) and new (Tony's) schema.

schema=metadata
script_path=$(readlink -f $0)
base=$(readlink -f ${script_path%/*}/..)
schema_base=${base}/build/text/1.2
old=${schema_base}/${schema}.rng
new=${schema_base}/${schema}-modular.rng
data=$1

xmllint --noout --relaxng ${old} ${data}
resultOld=$?
xmllint --noout --relaxng ${new} ${data}
resultNew=$?

if [[ $resultOld -ne $resultNew ]]
then
    echo "$resultOld $resultNew $data"
fi





