#!/bin/bash

errorlog=errors.log
schema=metadata
script_path=$(readlink -f $0)
base=$(readlink -f ${script_path%/*}/..)
schema_base=${base}/build/text/1.2
old=${schema_base}/${schema}.rng
new=${schema_base}/${schema}-modular.rng

rm -f *.log
touch $errorlog output1.log output2.log invalid.log

#set -x
for data in `ls /media/data/mirror/dbl/private/entries/text/*/*/*/metadata.xml`
do
    #xmllint --noout --relaxng ${old} ${data} |& cat >> output1.log #messes up result parsing
    xmllint --noout --relaxng ${old} ${data} 2>>output1.log
    resultOld=$?
    #xmllint --noout --relaxng ${new} ${data} |& cat >> output2.log
    xmllint --noout --relaxng ${new} ${data} 2>>output2.log
    resultNew=$?

    if [[ $resultOld -ne $resultNew ]]
    then
        echo "$resultOld $resultNew $data" >> ${errorlog}
        echo "FAILED: $data"
    else
        echo "OK:     $data"
    fi

    if [[ $resultOld -ne 0 ]]
    then echo "$data" >> invalid.log
    fi
done
    
